# Generated by Django 4.0.2 on 2024-03-06 01:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('requires_rendering', models.BooleanField(default=False, help_text="Set this to true, when the 'body' field contains Django template code that requires rendering")),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('permalink', models.CharField(help_text='Allowed characters: Need to start with a letter followed by letter, number and underscore', max_length=80, unique=True)),
                ('heading', models.CharField(help_text='max length: 200', max_length=200)),
                ('introduction', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
