# Generated by Django 5.1.4 on 2025-11-09 15:43

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The asset will be made available using this key as a context name. Only use one word or multiple words with underscore. Allowed letters: * Uppercase Letters * Lowercase Letters * Numbers (cannot be the first digit)  * Underscore. Max length: 128 characters.",
                        max_length=128,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="You can use this using the full url which can be found after saving the data. This also will be available for your homepage sections or posts as context variable where key is the name of the context variable.",
                        upload_to="assets/",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional: A note to yourself of where or how this can be used.",
                        null=True,
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.postdetail",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
