# Generated by Django 4.0.2 on 2024-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postdetail_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='introduction',
            field=models.CharField(max_length=400),
        ),
    ]
