# Generated by Django 5.1.4 on 2025-12-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_postasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttag",
            name="label",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
