# Generated by Django 4.0.2 on 2024-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_postdetail_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='introduction',
            field=models.TextField(),
        ),
    ]
