# Generated by Django 4.0.2 on 2024-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_postdetail_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postdetail',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='postdetail',
            name='requires_rendering',
            field=models.BooleanField(default=False, help_text="Set this to true, when the 'content' field contains Django template code that requires rendering"),
        ),
    ]
