# Generated by Django 6.0 on 2025-12-28 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_postasset_is_active_postasset_is_static"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostAsset",
        ),
    ]
