# Generated by Django 4.0.2 on 2024-03-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_body_postdetail_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
