# Generated by Django 4.0.2 on 2024-03-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postdetail_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdetail',
            name='include_sublinks',
            field=models.BooleanField(default=True, help_text='Post sublinks will be generated from any header tag and will aprear in Post Content section'),
        ),
    ]
