# Generated by Django 4.0.2 on 2024-03-09 17:08

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postdetail_include_sublinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=64)),
                ('color', models.CharField(help_text='Hex code for background color', max_length=20)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='postdetail',
            options={'ordering': ['-publish_date', '-created']},
        ),
        migrations.AddField(
            model_name='postdetail',
            name='tags',
            field=models.ManyToManyField(to='posts.PostTags'),
        ),
    ]
