# Generated by Django 4.0.2 on 2024-03-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_posttags_alter_postdetail_options_postdetail_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttags',
            name='bg_color',
            field=models.CharField(default='grey', help_text='css color (hex, rgb or color name) for background color', max_length=20),
        ),
        migrations.AlterField(
            model_name='posttags',
            name='color',
            field=models.CharField(default='white', help_text='css color (hex, rgb or color name) for text color', max_length=20),
        ),
    ]
