# Generated by Django 4.0.2 on 2024-03-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_posttags_bg_color_alter_posttags_color'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostTags',
            new_name='PostTag',
        ),
    ]
