# Generated by Django 4.0.2 on 2024-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_posttags_posttag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdetail',
            options={'ordering': ['feature', '-publish_date', '-created']},
        ),
        migrations.AddField(
            model_name='postdetail',
            name='feature',
            field=models.IntegerField(default=0, help_text='This value will help it sort in the post list page. Higher value has more priority.'),
        ),
    ]
