# Generated by Django 4.0.2 on 2024-03-10 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_postdetail_options_postdetail_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postdetail',
            options={'ordering': ['-feature', '-publish_date', '-created']},
        ),
    ]
