# Generated by Django 4.0.2 on 2024-03-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_postdetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdetail',
            name='tags',
            field=models.ManyToManyField(blank=True, to='posts.PostTag'),
        ),
    ]
