# Generated by Django 4.0.2 on 2022-03-30 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=40)),
                ('serial', models.FloatField()),
                ('body', models.CharField(max_length=3500)),
                ('upadte_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectposts')),
            ],
        ),
    ]
