# Generated by Django 4.0.2 on 2022-03-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=500)),
                ('url_name', models.CharField(default='details', max_length=40)),
                ('url_param', models.CharField(max_length=40, unique=True)),
                ('serial', models.FloatField(null=True)),
                ('body', models.CharField(max_length=7000, null=True)),
                ('update_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectposts')),
            ],
        ),
    ]
