# Generated by Django 4.0.2 on 2022-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectposts_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectposts',
            old_name='upadte_date',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='body',
            field=models.CharField(max_length=3500, null=True),
        ),
    ]
