# Generated by Django 4.0.2 on 2022-04-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectposts_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposts',
            name='body',
            field=models.CharField(blank=True, max_length=7000, null=True),
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectposts'),
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='serial',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
