# Generated by Django 4.0.2 on 2022-04-02 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectposts_body_alter_projectposts_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectposts',
            name='is_parent',
        ),
    ]
