# Generated by Django 4.0.2 on 2022-04-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projectposts_is_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectposts',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
