# Generated by Django 4.0.2 on 2022-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectposts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposts',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
