# Generated by Django 4.0.2 on 2022-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectposts_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectposts',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='update_date',
            field=models.DateField(auto_now=True),
        ),
    ]
