# Generated by Django 4.0.2 on 2023-01-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_Auto_update_date_and_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectposts',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='projectposts',
            name='url_name',
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.projectposts'),
        ),
        migrations.AlterField(
            model_name='projectposts',
            name='url_param',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
