# Generated by Django 6.0 on 2025-12-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteasset",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="siteasset",
            name="is_static",
            field=models.BooleanField(default=True),
        ),
    ]
