# Generated by Django 4.0.2 on 2024-03-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: A note to yourself of where or how this can be used.', null=True),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='file',
            field=models.FileField(help_text='You can use this using the full url which can be found after saving the data. This also will be available for your homepage sections or posts as context variable where key is the name of the context variable.', upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='key',
            field=models.CharField(help_text='The asset will be made available using this key as a context name. Only use one word or multiple words with underscore. Allowed letters: * Uppercase Letters * Lowercase Letters * Numbers (cannot be the first digit)  * Underscore. Max length: 128 characters.', max_length=128),
        ),
    ]
