# Generated by Django 6.0 on 2025-12-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_siteasset_is_active_siteasset_is_static"),
        ("pages", "0003_alter_pageasset_page"),
        ("posts", "0004_postasset_is_active_postasset_is_static"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteasset",
            name="homepage_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.homepagesection",
            ),
        ),
        migrations.AddField(
            model_name="siteasset",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.staticpage",
            ),
        ),
        migrations.AddField(
            model_name="siteasset",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="posts.postdetail",
            ),
        ),
    ]
