# Generated by Django 4.0.2 on 2023-02-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basehome', '0002_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='key',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
