# .circleci/config.yaml
version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.10.3
        user: root
        environment:
          - MYSQL_DATABASE: test_test
          - MYSQL_USER: root
          - MYSQL_PASSWORD: test
          - MYSQL_HOST: 127.0.0.1
          - MYSQL_PORT: 3306
          - ALLOWED_HOST: '*'

      - image: mysql:5.7
        command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_bin"]
        environment:
            - MYSQL_ROOT_PASSWORD: test
            - MYSQL_DATABASE: test_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            apt-get update -qq && apt-get install libjpeg-dev zlib1g-dev
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
