# Generated by Django 4.0.2 on 2024-03-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='render_django_template',
            field=models.BooleanField(default=False, help_text="Set this to true, when the 'body' field contains Django template code that requires rendering"),
        ),
    ]
