# Generated by Django 6.0 on 2025-12-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_pageasset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pageasset",
            name="page",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated page for this asset. If left blank, the asset is considered home page asset.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.staticpage",
            ),
        ),
    ]
