# Generated by Django 4.0.2 on 2024-03-06 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepagesection_render_django_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='render_django_template',
            new_name='requires_rendering',
        ),
    ]
