# Generated by Django 6.0 on 2025-12-28 01:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_alter_pageasset_page"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageAsset",
        ),
    ]
