# Generated by Django 4.0.2 on 2024-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_render_django_template_homepagesection_requires_rendering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='requires_rendering',
            field=models.BooleanField(default=False, help_text="Set this to true, when the 'content' field contains Django template code that requires rendering"),
        ),
    ]
