# Generated by Django 6.0 on 2025-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_delete_pageasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesection",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
