# Generated by Django 4.0.2 on 2024-03-10 03:52

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_body_homepagesection_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('requires_rendering', models.BooleanField(default=False, help_text="Set this to true, when the 'content' field contains Django template code that requires rendering")),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('permalink', models.CharField(help_text='Allowed characters: Need to start with a letter followed by letter, number and underscore', max_length=80, unique=True)),
                ('heading', models.CharField(help_text='max length: 200', max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('navbar_title', models.CharField(blank=True, help_text="When populated, this field will display the specified title on the navbar before 'POSTS'.", max_length=32, null=True)),
                ('navbar_serial', models.IntegerField(default=0, help_text='Not effective if no navbar_title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
