# Generated by Django 4.0.2 on 2024-03-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_staticpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticpage',
            name='publish_date',
        ),
    ]
