# Generated by Django 4.0.2 on 2022-04-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BlogsPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=500)),
                ('url_param', models.CharField(max_length=80, unique=True)),
                ('body', models.CharField(max_length=7000)),
                ('update_date', models.DateField()),
                ('publish_date', models.DateField()),
                ('tags', models.ManyToManyField(to='blogs.BlogsTags')),
            ],
        ),
    ]
