# Generated by Django 4.0.2 on 2022-04-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsposts',
            name='tags',
        ),
        migrations.DeleteModel(
            name='BlogsTags',
        ),
    ]
