# Generated by Django 4.0.2 on 2022-04-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogstags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogstags',
            name='value',
            field=models.IntegerField(default=1),
        ),
    ]
