# Generated by Django 4.0.2 on 2022-04-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogsposts_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsposts',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
