# Generated by Django 4.0.2 on 2022-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blogsposts_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsposts',
            name='body',
            field=models.TextField(),
        ),
    ]
