# Generated by Django 4.0.2 on 2024-03-01 09:53

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('navbar_titile', models.CharField(max_length=128)),
                ('heading', models.CharField(max_length=512)),
                ('body', models.TextField()),
                ('serial', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('serial', 'created'),
            },
        ),
    ]
