# Generated by Django 4.0.2 on 2024-03-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesection',
            old_name='navbar_titile',
            new_name='navbar_title',
        ),
    ]
