name: SSH and Run Command

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ closed ]
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Execute SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_SSH_IP }}
        username: ${{ secrets.DROPLET_SSH_USER }}
        password: ${{ secrets.DROPLET_SSH_PASSWORD }}
        script: |
          mpupdate
